#!/bin/bash

# --- Configuration ---
DEFAULT_OLLAMA_HOST="192.168.8.90"
#DEFAULT_MODEL="qwen3:30b-a3b-thinking-2507-fp16"
DEFAULT_MODEL="gpt-oss:120b"

SOURCE_FOLDER="blog_post_ideas"
DESTINATION_FOLDER="blog_post_drafts"

# --- Check for required tools ---
if ! command -v curl &> /dev/null; then
    echo "Error: curl is not installed. Please install it to continue."
    exit 1
fi
if ! command -v jq &> /dev/null; then
    echo "Error: jq is not installed. Please install it to continue."
    exit 1
fi

mkdir -p blog_post_full
total_files=$(find $SOURCE_FOLDER -maxdepth 1 -type f -name "*.md" | wc -l)
current=0

for idea_file in $SOURCE_FOLDER/*.md; do
    current=$((current + 1))
    echo "[$current/$total_files] Processing $(basename "$idea_file")"
    idea_content=$(cat "$idea_file")
    context_content=$(cat context.md)

    voice="You are a seasoned freelance journalist with 15 years of experience writing for magazines like The Atlantic or Wired. \
    Your writing style is engaging, conversational, and human-like, with varied sentence lengths, occasional idioms or slang, and subtle \
    imperfections like minor tangents or rhetorical questions to make it feel authentic and less robotic. \
    Avoid repetitive phrases, overly formal language, or predictable structures \
    (e.g., don't start every paragraph with a topic sentence). Incorporate personal anecdotes, opinions, or hypothetical scenarios \
    where they fit naturally to add depth. Do not use clichés like 'in today's fast-paced world' or end with generic summaries. \
    Research the topic briefly in your mind and reference real-world examples or sources subtly, as a human writer would. \
    Now, write an article on the topic requested, titled [suggested title]. \
    Make it informative, balanced, and engaging for a general audience, ensuring it's not obvious that this was generated by AI. \
    aim for the warmth and nuance of handwritten notes turned into a draft."

    voice2="Write in the voice of a New Yorker editor: sophisticated, witty, and introspective.\
    conversational yet authoritative, engaging and personality-driven \
    varied sentence lengths, occasional idioms or slang, and subtle imperfections like minor tangents or rhetorical questions to make it feel authentic \
    inform, entertain, and provoke thought"

    system_prompt="Reasoning: high ,  extra context $context_content. Writing Style should be: $voice2"
    
    prompt="Using Construkted Reality's content marketing strategy, create a full blog post using the following draft: $idea_content. \
    Visit all URLs listed in the SOURCE section and use for context. \
    Display the sources used in the response. \
    Focus on validating the user pain point hand take every opportunity to mentioning our product Construkted Reality. \
    For images, create numeric placeholders in the body of the post, and at the bottom of the post create an **Image Prompt Summary** section where the detailed prompts specified. Image generation prompts will be used in an llm for image generation. \
    Do not use tables unless absolutely necessary. "

    # Prepare the JSON payload
    JSON_PAYLOAD=$(jq -n \
        --arg model "$DEFAULT_MODEL" \
        --arg prompt "$prompt" \
        --arg system "$system_prompt" \
        '{model: $model, prompt: $prompt, system: $system, stream: false}')

    # Send the request
    OLLAMA_URL="http://${DEFAULT_OLLAMA_HOST}:11434/api/generate"
    response=$(curl -s -X POST "$OLLAMA_URL" -d "$JSON_PAYLOAD" | jq -r '.response')
    
    # Save the response
    echo "$response" > "$DESTINATION_FOLDER/$(basename "$idea_file")"
    #echo $JSON_PAYLOAD
    #echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ \n"
    #echo "$response"

done
